### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by NathanTheGr8**
Added favicon and icons for different browsers and platforms #5 

Note that in /public/img/icons/manifest.json I hard coded a the name to "Manage This" I am not sure how to make it dynamically the app title.

### CODE REVIEW

**Comment by NathanTheGr8** [comment]
I am having trouble testing this. My browser seems to have my old ones cached. It worked when I did the exact same thing on my own personal one.

**Comment by NathanTheGr8** [comment]
app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));

I don't understand that line. Is path something I need to declare somewhere? If throws and error when I uncomment this line, 19 in app.js.

**Comment by NathanTheGr8** [comment]
I would like to use [real-favicon's gulp api](http://realfavicongenerator.net/favicon_result?file_id=p1aqcnaejq1h2g1v47fd2j9o1a716#.V7SbaJMrKL9) to make a custom favicon. I understand how to generate and place the icons in the app. However, how do I inject the markup into the layouts.hbs file(step 5 & 6)? I don't know or understand if gulp will be able to inject into that file. Also how it knows were to put the new tags.

**Comment by onedr0p** [comment]
In any case I'll merge this in. I don't see anything out of order in this PR. For your other PR, I would close it and make a new PR with the changes you want to the navbar.

**Comment by NathanTheGr8** [comment]
I am not sure I understand. You want me to close the other one and refork the repo and make the changes again? Why can't I just merge master into mine so that I get these changes?

**Pull request merged**
